// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjErLEWzEn774MDz0ZeKe3Wt5luwy3RQ',
    appId: '1:312743817245:web:4fe54f0796a684d5c496f4',
    messagingSenderId: '312743817245',
    projectId: 'video-app-huynguyen',
    authDomain: 'video-app-huynguyen.firebaseapp.com',
    storageBucket: 'video-app-huynguyen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDifrAX6CVASqPgnS-GPJBiIi1RSYqzWp0',
    appId: '1:312743817245:android:f7ad4a2f3dcdfe0ec496f4',
    messagingSenderId: '312743817245',
    projectId: 'video-app-huynguyen',
    storageBucket: 'video-app-huynguyen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZndxfMMFkbjQO_A-d8c45nAjJAnNMxBw',
    appId: '1:312743817245:ios:5ffd3ecc02cbc6a6c496f4',
    messagingSenderId: '312743817245',
    projectId: 'video-app-huynguyen',
    storageBucket: 'video-app-huynguyen.appspot.com',
    iosBundleId: 'com.example.videoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZndxfMMFkbjQO_A-d8c45nAjJAnNMxBw',
    appId: '1:312743817245:ios:5ffd3ecc02cbc6a6c496f4',
    messagingSenderId: '312743817245',
    projectId: 'video-app-huynguyen',
    storageBucket: 'video-app-huynguyen.appspot.com',
    iosBundleId: 'com.example.videoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHjErLEWzEn774MDz0ZeKe3Wt5luwy3RQ',
    appId: '1:312743817245:web:33e4e2e425ab4d7fc496f4',
    messagingSenderId: '312743817245',
    projectId: 'video-app-huynguyen',
    authDomain: 'video-app-huynguyen.firebaseapp.com',
    storageBucket: 'video-app-huynguyen.appspot.com',
  );

}